affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: !!python/object/apply:numpy._core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  WgAAAAAAAAA=
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 57
symbolic.funs_name.0:
- - x
  - x
  - sin
  - x
  - x
  - x
  - exp
  - x
  - x
  - sin
  - x^2
  - exp
  - tan
symbolic_enabled: true
width:
- - 13
  - 0
- - 1
  - 0
